{
  "hash": "8fde8b482c82d59c01ebff7e42b260f8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Jinheng\"\ndate: 2025-10-07\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\nlibrary(knitr)\n\ncensus_api_key(\"42bf8a20a3df1def380f330cf7edad0dd5842ce6\", install = TRUE, overwrite=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"42bf8a20a3df1def380f330cf7edad0dd5842ce6\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load spatial data\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `/Users/jinhengcen/Documents/portfolio-setup-CenJinHeng/assignments/assignment_2/data/Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/jinhengcen/Documents/portfolio-setup-CenJinHeng/assignments/assignment_2/data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\n# Check that all data loaded correctly\npa_counties\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n   OBJECTID MSLINK COUNTY_NAM COUNTY_NUM FIPS_COUNT COUNTY_ARE COUNTY_PER\n1       336     46 MONTGOMERY         46        091       <NA>       <NA>\n2       337      8   BRADFORD         08        015       <NA>       <NA>\n3       338      9      BUCKS         09        017       <NA>       <NA>\n4       339     58      TIOGA         58        117       <NA>       <NA>\n5       340     59      UNION         59        119       <NA>       <NA>\n6       341     60    VENANGO         60        121       <NA>       <NA>\n7       342     62 WASHINGTON         62        125       <NA>       <NA>\n8       343     63      WAYNE         63        127       <NA>       <NA>\n9       344     42     MCKEAN         42        083       <NA>       <NA>\n10      345     43     MERCER         43        085       <NA>       <NA>\n   NUMERIC_LA COUNTY_N_1 AREA_SQ_MI SOUND SPREAD_SHE IMAGE_NAME NOTE_FILE VIDEO\n1           5         46   487.4271  <NA>       <NA>   poll.bmp      <NA>  <NA>\n2           2          8  1161.3379  <NA>       <NA>   poll.bmp      <NA>  <NA>\n3           5          9   622.0836  <NA>       <NA>   poll.bmp      <NA>  <NA>\n4           2         58  1137.2480  <NA>       <NA>   poll.bmp      <NA>  <NA>\n5           2         59   319.1893  <NA>       <NA>   poll.bmp      <NA>  <NA>\n6           3         60   683.3676  <NA>       <NA>   poll.bmp      <NA>  <NA>\n7           1         62   862.1077  <NA>       <NA>   poll.bmp      <NA>  <NA>\n8           2         63   750.8286  <NA>       <NA>   poll.bmp      <NA>  <NA>\n9           1         42   985.2700  <NA>       <NA>   poll.bmp      <NA>  <NA>\n10          3         43   682.3598  <NA>       <NA>   poll.bmp      <NA>  <NA>\n   DISTRICT_N PA_CTY_COD MAINT_CTY_ DISTRICT_O                       geometry\n1          06         46          4        6-4 MULTIPOLYGON (((-8398884 48...\n2          03         08          9        3-9 MULTIPOLYGON (((-8558633 51...\n3          06         09          1        6-1 MULTIPOLYGON (((-8367360 49...\n4          03         59          7        3-7 MULTIPOLYGON (((-8558633 51...\n5          03         60          8        3-8 MULTIPOLYGON (((-8562865 49...\n6          01         61          5        1-5 MULTIPOLYGON (((-8870781 50...\n7          12         63          4       12-4 MULTIPOLYGON (((-8935296 48...\n8          04         64          6        4-6 MULTIPOLYGON (((-8368003 50...\n9          02         42          5        2-5 MULTIPOLYGON (((-8705967 51...\n10         01         43          4        1-4 MULTIPOLYGON (((-8956031 50...\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8960798 ymin: 4829916 xmax: -8334160 ymax: 5181077\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n                  CHIEF_EXEC              CHIEF_EX_1\n1              Peter J Adamo               President\n2           Autumn DeShields Chief Executive Officer\n3               Shawn Parekh Chief Executive Officer\n4                DIANE HRITZ Chief Executive Officer\n5             Tim Harclerode Chief Executive Officer\n6  Richard McLaughlin MD MBA Chief Executive Officer\n7             Laura Murnyack             Interim CEO\n8                  Adam Beck Chief Executive Officer\n9                Pamela Keen Chief Executive Officer\n10              Mark Papalia           President/CEO\n                                 FACILITY_U LONGITUDE       COUNTY\n1              https://www.phhealthcare.org -79.91131   Washington\n2                 https://www.malvernbh.com -75.17005 Philadelphia\n3            https://roxboroughmemorial.com -75.20963 Philadelphia\n4                https://www.ashospital.net -80.27907   Washington\n5                 https://www.conemaugh.org -79.02513     Somerset\n6                   https://towerhealth.org -75.61213   Montgomery\n7         https://bucktailmedicalcenter.org -77.73649      Clinton\n8  https://www.selectspecialtyhospitals.com -76.88013      Dauphin\n9          https://www.childrenshomepgh.org -79.93736    Allegheny\n10    https://www.kanecommunityhospital.com -78.81705       McKean\n                                                  FACILITY_N\n1                                  Penn Highlands Mon Valley\n2                                  MALVERN BEHAVIORAL HEALTH\n3                               Roxborough Memorial Hospital\n4                                 ADVANCED SURGICAL HOSPITAL\n5                    DLP Conemaugh Meyersdale Medical Center\n6                                    Pottstown Hospital, LLC\n7                                    Bucktail medical Center\n8  SELECT SPECIALTY HOSPITAL CENTRAL PENNSYLVANIA HARRISBURG\n9                          The Children's Home of Pittsburgh\n10              University of Pittsburgh Medical Center Kane\n                           STREET   CITY_OR_BO LATITUDE   TELEPHONE_ ZIP_CODE\n1          1163 Country Club Road  Monongahela 40.18193 724-258-1000    15063\n2  1930 South Broad Street Unit 4 Philadelphia 39.92619 610-480-8919    19145\n3               5800 Ridge Avenue Philadelphia 40.02869 215-483-9900    19128\n4        100 TRICH DRIVE\\nSUITE 1   WASHINGTON 40.15655   7248840710    15301\n5              200 Hospital Drive   Meyersdale 39.80913 814-634-5911    15552\n6           1600 East High Street    Pottstown 40.24273   6103277000    19464\n7                1001 Pine Street       Renovo 41.32789 570-923-1000    17764\n8          111 South Front Street   Harrisburg 40.25841 717-724-6604    17110\n9                5324 Penn Avenue   Pittsburgh 40.46424 412-441-4884    15224\n10                4372 US Route 6         Kane 41.67188   8148378585    16735\n                   geometry\n1  POINT (-8895686 4892415)\n2  POINT (-8367892 4855223)\n3  POINT (-8372298 4870112)\n4  POINT (-8936626 4888717)\n5  POINT (-8797037 4838244)\n6  POINT (-8417104 4901278)\n7  POINT (-8653586 5060826)\n8  POINT (-8558256 4903566)\n9  POINT (-8898587 4933636)\n10 POINT (-8773874 5111954)\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3445 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963433 ymin: 4825308 xmax: -8314399 ymax: 5201489\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n   STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID   NAME\n1       42      001  031101 1400000US42001031101 42001031101 311.01\n2       42      013  100400 1400000US42013100400 42013100400   1004\n3       42      013  100500 1400000US42013100500 42013100500   1005\n4       42      013  100800 1400000US42013100800 42013100800   1008\n5       42      013  101900 1400000US42013101900 42013101900   1019\n6       42      011  011200 1400000US42011011200 42011011200    112\n7       42      011  000200 1400000US42011000200 42011000200      2\n8       42      011  011500 1400000US42011011500 42011011500    115\n9       42      011  000600 1400000US42011000600 42011000600      6\n10      42      011  001900 1400000US42011001900 42011001900     19\n              NAMELSAD STUSPS   NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1  Census Tract 311.01     PA Adams County Pennsylvania   CT 3043185      0\n2    Census Tract 1004     PA Blair County Pennsylvania   CT  993724      0\n3    Census Tract 1005     PA Blair County Pennsylvania   CT 1130204      0\n4    Census Tract 1008     PA Blair County Pennsylvania   CT  996553      0\n5    Census Tract 1019     PA Blair County Pennsylvania   CT  573726      0\n6     Census Tract 112     PA Berks County Pennsylvania   CT 1539365   9308\n7       Census Tract 2     PA Berks County Pennsylvania   CT 1949529 159015\n8     Census Tract 115     PA Berks County Pennsylvania   CT 1978380  12469\n9       Census Tract 6     PA Berks County Pennsylvania   CT 1460473      0\n10     Census Tract 19     PA Berks County Pennsylvania   CT  182420      0\n                         geometry\n1  MULTIPOLYGON (((-8575060 48...\n2  MULTIPOLYGON (((-8730207 49...\n3  MULTIPOLYGON (((-8729297 49...\n4  MULTIPOLYGON (((-8728636 49...\n5  MULTIPOLYGON (((-8728378 49...\n6  MULTIPOLYGON (((-8455198 49...\n7  MULTIPOLYGON (((-8455907 49...\n8  MULTIPOLYGON (((-8460184 49...\n9  MULTIPOLYGON (((-8450851 49...\n10 MULTIPOLYGON (((-8451174 49...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n223\n- How many census tracts?\n3445\n- What coordinate reference system is each dataset in?\nI converted them all in WGS 84 / Pseudo-Mercator\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\ntract_data <- get_acs(\n  geography = \"tract\",\n  state     = \"42\",\n  variables = c(\n    total_population = \"B01003_001\",\n    median_household_income = \"B19013_001\"\n  ),\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nage_data <- get_acs(\n  geography = \"tract\",\n  state     = \"42\",\n  variables = c(\n    male_65 <- c(\"B01001_020\",\"B01001_021\",\"B01001_022\",\"B01001_023\",\"B01001_024\",\"B01001_025\"),\n    female_65 <- c(\"B01001_044\",\"B01001_045\",\"B01001_046\",\"B01001_047\",\"B01001_048\",\"B01001_049\")\n  ),\n  year = 2023,\n  survey = \"acs5\",\n) %>% \n  group_by (GEOID) %>%\n  summarise(pop_65 = sum(estimate, na.rm = TRUE))\n\nage_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,446 × 2\n   GEOID       pop_65\n   <chr>        <dbl>\n 1 42001030101    577\n 2 42001030103    570\n 3 42001030104    858\n 4 42001030200   1070\n 5 42001030300    782\n 6 42001030400   1231\n 7 42001030500    788\n 8 42001030600   1129\n 9 42001030700   1216\n10 42001030801    762\n# ℹ 3,436 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\ntract_data <- tract_data %>%\n  left_join(age_data, by = \"GEOID\")\n\ntract_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,446 × 7\n   GEOID       NAME   total_populationE total_populationM median_household_inc…¹\n   <chr>       <chr>              <dbl>             <dbl>                  <dbl>\n 1 42001030101 Censu…              2666                29                  82716\n 2 42001030103 Censu…              2414               332                 111227\n 3 42001030104 Censu…              3417               333                  66848\n 4 42001030200 Censu…              5379               502                  72431\n 5 42001030300 Censu…              4390               205                  84643\n 6 42001030400 Censu…              5557               245                  97694\n 7 42001030500 Censu…              3761               232                  69583\n 8 42001030600 Censu…              4884                30                  85625\n 9 42001030700 Censu…              6674               356                  80585\n10 42001030801 Censu…              3357               320                  82500\n# ℹ 3,436 more rows\n# ℹ abbreviated name: ¹​median_household_incomeE\n# ℹ 2 more variables: median_household_incomeM <dbl>, pop_65 <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\ntract_data %>%\n  summarise(missing_data = sum(is.na(median_household_incomeE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  missing_data\n         <int>\n1           66\n```\n\n\n:::\n\n```{.r .cell-code}\ntract_data %>%\n  summarise(median_income = sum(median(median_household_incomeE, na.rm = TRUE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  median_income\n          <dbl>\n1        72944.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join to tract boundaries\n\ncensus_tracts_joined <- census_tracts %>%\n  left_join(tract_data, by = \"GEOID\")\n```\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n2023\n- How many tracts have missing income data?\n66\n- What is the median income across all PA census tracts?\n72943.5\t\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n\ncensus_tracts_joined <- census_tracts_joined %>%\n  mutate(\n    percentage_65 = pop_65/total_populationE\n  )\n\nvulnerable_tracts <- census_tracts_joined %>%\n  filter(median_household_incomeE < 48000,\n         percentage_65 > 0.20\n         )\n```\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\nFor the income threshold, I chose 48,000 based on the 2025 poverty guidelines by the USCIS. For a family with four people, 150% of the federal poverty level is $48,225.\n- What elderly population threshold did you choose and why?\nFor the age threshold, I chose the percentage of people over 65 years old is over 20%, which can be seen as an elderly community.\n- How many tracts meet your vulnerability criteria?\n126\n- What percentage of PA census tracts are considered vulnerable by your definition?\nthe percentage of vulnerable tracts = 126 / 3445 = 3.66%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n\nvulnerable_tracts_proj <- vulnerable_tracts %>%\n  st_transform(5070) # 5070 is for the whole country. For south PA alone, we can use 3365, which is more precise.\n\nhospitals_proj <- hospitals %>%\n  st_transform(5070)\n\n\n# Calculate distance from each tract centroid to nearest hospital\n\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n\nnearest_hospital_idx <- st_nearest_feature(tract_centroids, hospitals_proj)\n\ndist_to_hospital <- st_distance(\n  tract_centroids,\n  hospitals_proj[nearest_hospital_idx, ],\n  by_element = TRUE\n)\n\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    dist_to_hospital = as.numeric(dist_to_hospital),\n    dist_to_hospital_mi = dist_to_hospital * 0.000621371\n  )\n\ndistant_data <- vulnerable_tracts_proj %>%\n  summarise(\n    avg_distance = mean(dist_to_hospital_mi, na.rm = TRUE),\n    max_dist = max(dist_to_hospital_mi, na.rm = TRUE),\n  )\n\ndistant_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1282205 ymin: 1990587 xmax: 1757922 ymax: 2252774\nProjected CRS: NAD83 / Conus Albers\n  avg_distance max_dist                       geometry\n1     2.803376 18.55538 MULTIPOLYGON (((1347636 204...\n```\n\n\n:::\n\n```{.r .cell-code}\nnum_over15 <- vulnerable_tracts_proj %>%\n  filter(dist_to_hospital_mi > 15) %>%\n  summarise(\n    n_over15 = n(),\n  )\n\nnum_over15\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1461788 ymin: 2192308 xmax: 1464364 ymax: 2193760\nProjected CRS: NAD83 / Conus Albers\n  n_over15                       geometry\n1        1 MULTIPOLYGON (((1461853 219...\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n2.8 miles\n- What is the maximum distance?\n18.6 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n1\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nundeserved <- vulnerable_tracts_proj %>%\n  filter(dist_to_hospital_mi > 15)\n\nundeserved \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 22 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1461788 ymin: 2192308 xmax: 1464364 ymax: 2193760\nProjected CRS: NAD83 / Conus Albers\n  STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID NAME.x\n1      42      023  960100 1400000US42023960100 42023960100   9601\n           NAMELSAD STUSPS     NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1 Census Tract 9601     PA Cameron County Pennsylvania   CT 1838256 107252\n                                           NAME.y total_populationE\n1 Census Tract 9601; Cameron County; Pennsylvania              2005\n  total_populationM median_household_incomeE median_household_incomeM pop_65\n1               134                    36167                     6116    504\n                        geometry percentage_65 dist_to_hospital\n1 MULTIPOLYGON (((1461853 219...     0.2513716            29862\n  dist_to_hospital_mi\n1            18.55538\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\nonly 1!\n- What percentage of vulnerable tracts are underserved?\n1/126 = 0.79%\n- Does this surprise you? Why or why not?\nNo, I looked at the distance data of the vulnerable tracts, most of them (92.9%) are under 10 miles (16000m). I think 15 miles is a very big number, so we just have one tract fulfill all the requirements.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts_proj, st_crs(pa_counties))\nundeserved  <- st_transform(undeserved , st_crs(pa_counties))\n\ncounties_num = census_tracts %>%\n  st_centroid() %>%\n  st_join(pa_counties%>% select(COUNTY_NAM)) %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    n_tract =  n(),\n  )%>%\n  arrange(n_tract)\n\ncounties_vuln <- vulnerable_tracts_proj %>%\n  st_centroid() %>%\n  st_join(pa_counties%>% select(COUNTY_NAM)) %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    n_vuln =  n(),\n    avg_dist_vuln_mi = mean(dist_to_hospital_mi, na.rm = TRUE),\n    total_vuln_pop = sum(pop_65, na.rm = TRUE)\n  ) %>%\n  arrange(desc(total_vuln_pop))\n\ncounties_unders <- undeserved %>%\n  st_centroid() %>%\n  st_join(pa_counties%>% select(COUNTY_NAM)) %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    n_unders =  n(),\n  ) %>%\n  arrange(desc(n_unders))\n\n\n\n# Aggregate statistics by county\n\ncounties_stat = counties_num %>%\n  left_join(counties_vuln, by = \"COUNTY_NAM\") %>%\n  left_join(counties_unders, by = \"COUNTY_NAM\") %>%\n  mutate(\n    percentage_unders = n_unders / n_vuln,\n    percentage_vuln = n_vuln / n_tract\n  )%>%\n  arrange(desc(percentage_vuln))\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nCAMERON is the highest, with 100% in the number.\nSince I only have 1 underserved tract, I would show top 5 counties with the highest percentage of vulnerable tracts:\n(1) CAMERON 50.0%\n(2) FAYETTE 19.4%\n(3) CAMBRIA 19.0%\n(4) JEFFERSON 15.4%\n(5) WARREN 15.4%\n- Which counties have the most vulnerable people living far from hospitals?\nPHILADELPHIA, with the number of 18022\n- Are there any patterns in where underserved counties are located?\nSince I only have 1 underserved tract, I would observe patterns of vulnerable counties.\n(1) Most of them are from rural areas with less tracts number, so they have higher percentage of vulnerable tracts\n(2) They have large numbers of vulnerable population, which means lots of low-income and old people living there. Most of them have number over 1000. \n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n# metrics for the priority: vulnerable index = normalized_number_of_vulnerable_tracts*0.3 + normalized_average_distant _hospital*0.5 + normalized_total_population*0.2\n\nscale_minmax <- function(x) {\n  rng <- range(x, na.rm = TRUE)\n  if (!is.finite(diff(rng)) || diff(rng) == 0) return(rep(0.5, length(x)))\n  (x - rng[1]) / diff(rng)\n}\n\ncounties_stat_index <- counties_stat %>%\n  mutate(\n    n_vuln_norm = scale_minmax(n_vuln),\n    avg_dist_vuln_mi_norm = scale_minmax(avg_dist_vuln_mi),\n    total_vuln_pop_norm = scale_minmax(total_vuln_pop),\n    percentage_vuln_norm = scale_minmax(percentage_vuln)\n  ) %>%\n   mutate(\n     vuln_index =\n       0.3  * n_vuln_norm +\n       0.5 * avg_dist_vuln_mi_norm +\n       0.2 * total_vuln_pop_norm\n   ) %>%\n  arrange(desc(vuln_index))\n\ncounties_stat_index\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 68 × 13\n   COUNTY_NAM     n_tract n_vuln avg_dist_vuln_mi total_vuln_pop n_unders\n   <chr>            <int>  <int>            <dbl>          <dbl>    <int>\n 1 ALLEGHENY          394     28            2.39           15213       NA\n 2 CAMERON              2      1           18.6              504        1\n 3 PHILADELPHIA       407     19            0.887          18022       NA\n 4 HUNTINGDON          13      1           14.2              730       NA\n 5 NORTHUMBERLAND      25      3           10.8             1603       NA\n 6 CAMBRIA             42      8            4.15            4588       NA\n 7 VENANGO             17      1            8.40             363       NA\n 8 FAYETTE             36      7            2.55            5780       NA\n 9 ERIE                72      7            2.35            5923       NA\n10 WARREN              13      2            6.19            1257       NA\n# ℹ 58 more rows\n# ℹ 7 more variables: percentage_unders <dbl>, percentage_vuln <dbl>,\n#   n_vuln_norm <dbl>, avg_dist_vuln_mi_norm <dbl>, total_vuln_pop_norm <dbl>,\n#   percentage_vuln_norm <dbl>, vuln_index <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n#make table\n\ncounties_table <- counties_stat_index %>%\n  select(\n    county_name = COUNTY_NAM,\n    vulnerable_index = vuln_index,\n    vulnerable_tract_number = n_vuln,\n    average_dist_to_hospital = avg_dist_vuln_mi,\n    total_vulnerable_pop = total_vuln_pop\n  ) %>%\n  mutate(\n    vulnerable_index = round(vulnerable_index, 3),\n    average_dist_to_hospital = round(average_dist_to_hospital, 2),\n    total_vulnerable_pop = comma(total_vulnerable_pop)\n  )%>%\n  arrange(desc(vulnerable_index))\n\nkable(\n  counties_table,\n  caption = \"PA County-level Vulnerability Summary\",\n  align = \"lcccc\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: PA County-level Vulnerability Summary\n\n|county_name    | vulnerable_index | vulnerable_tract_number | average_dist_to_hospital | total_vulnerable_pop |\n|:--------------|:----------------:|:-----------------------:|:------------------------:|:--------------------:|\n|ALLEGHENY      |      0.519       |           28            |           2.39           |        15,213        |\n|CAMERON        |      0.502       |            1            |          18.56           |         504          |\n|PHILADELPHIA   |      0.409       |           19            |           0.89           |        18,022        |\n|HUNTINGDON     |      0.383       |            1            |          14.18           |         730          |\n|NORTHUMBERLAND |      0.321       |            3            |          10.81           |        1,603         |\n|CAMBRIA        |      0.226       |            8            |           4.15           |        4,588         |\n|VENANGO        |      0.218       |            1            |           8.40           |         363          |\n|FAYETTE        |      0.183       |            7            |           2.55           |        5,780         |\n|ERIE           |      0.179       |            7            |           2.35           |        5,923         |\n|WARREN         |      0.178       |            2            |           6.19           |        1,257         |\n|LANCASTER      |      0.175       |            1            |           6.60           |        1,034         |\n|LUZERNE        |      0.153       |            6            |           2.51           |        4,195         |\n|WESTMORELAND   |      0.150       |            6            |           2.86           |        3,057         |\n|LAWRENCE       |      0.149       |            3            |           4.52           |        1,793         |\n|NORTHAMPTON    |      0.130       |            1            |           5.03           |         850          |\n|CLINTON        |      0.127       |            1            |           4.89           |         913          |\n|DELAWARE       |      0.120       |            6            |           1.32           |        4,179         |\n|LACKAWANNA     |      0.104       |            5            |           1.67           |        2,871         |\n|LEHIGH         |      0.092       |            1            |           3.42           |        1,417         |\n|BEAVER         |      0.076       |            2            |           2.53           |        1,291         |\n|BLAIR          |      0.076       |            2            |           2.18           |        2,079         |\n|INDIANA        |      0.070       |            1            |           2.63           |        1,447         |\n|WASHINGTON     |      0.068       |            2            |           2.39           |         915          |\n|LYCOMING       |      0.066       |            1            |           2.90           |         470          |\n|MERCER         |      0.063       |            3            |           1.42           |        1,866         |\n|JEFFERSON      |      0.057       |            2            |           1.72           |        1,566         |\n|MIFFLIN        |      0.038       |            1            |           1.87           |         516          |\n|YORK           |      0.028       |            1            |           1.55           |         425          |\n|CRAWFORD       |      0.015       |            1            |           0.93           |         787          |\n|WAYNE          |      0.014       |            1            |           0.83           |         951          |\n|SOMERSET       |      0.008       |            1            |           0.82           |         399          |\n|BUTLER         |      0.000       |            1            |           0.56           |         400          |\n|NA             |        NA        |           NA            |            NA            |          NA          |\n|FOREST         |        NA        |           NA            |            NA            |          NA          |\n|FULTON         |        NA        |           NA            |            NA            |          NA          |\n|MONTOUR        |        NA        |           NA            |            NA            |          NA          |\n|SULLIVAN       |        NA        |           NA            |            NA            |          NA          |\n|JUNIATA        |        NA        |           NA            |            NA            |          NA          |\n|POTTER         |        NA        |           NA            |            NA            |          NA          |\n|WYOMING        |        NA        |           NA            |            NA            |          NA          |\n|SNYDER         |        NA        |           NA            |            NA            |          NA          |\n|ELK            |        NA        |           NA            |            NA            |          NA          |\n|GREENE         |        NA        |           NA            |            NA            |          NA          |\n|PERRY          |        NA        |           NA            |            NA            |          NA          |\n|TIOGA          |        NA        |           NA            |            NA            |          NA          |\n|UNION          |        NA        |           NA            |            NA            |          NA          |\n|BEDFORD        |        NA        |           NA            |            NA            |          NA          |\n|MCKEAN         |        NA        |           NA            |            NA            |          NA          |\n|SUSQUEHANNA    |        NA        |           NA            |            NA            |          NA          |\n|CLARION        |        NA        |           NA            |            NA            |          NA          |\n|BRADFORD       |        NA        |           NA            |            NA            |          NA          |\n|COLUMBIA       |        NA        |           NA            |            NA            |          NA          |\n|CARBON         |        NA        |           NA            |            NA            |          NA          |\n|ARMSTRONG      |        NA        |           NA            |            NA            |          NA          |\n|CLEARFIELD     |        NA        |           NA            |            NA            |          NA          |\n|PIKE           |        NA        |           NA            |            NA            |          NA          |\n|ADAMS          |        NA        |           NA            |            NA            |          NA          |\n|FRANKLIN       |        NA        |           NA            |            NA            |          NA          |\n|LEBANON        |        NA        |           NA            |            NA            |          NA          |\n|CENTRE         |        NA        |           NA            |            NA            |          NA          |\n|SCHUYLKILL     |        NA        |           NA            |            NA            |          NA          |\n|MONROE         |        NA        |           NA            |            NA            |          NA          |\n|CUMBERLAND     |        NA        |           NA            |            NA            |          NA          |\n|DAUPHIN        |        NA        |           NA            |            NA            |          NA          |\n|BERKS          |        NA        |           NA            |            NA            |          NA          |\n|CHESTER        |        NA        |           NA            |            NA            |          NA          |\n|BUCKS          |        NA        |           NA            |            NA            |          NA          |\n|MONTGOMERY     |        NA        |           NA            |            NA            |          NA          |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n# I use percentage of vulnerable tract here\n\nlibrary(ggplot2)\n\ncounties_stat_sf <- pa_counties %>%\n  select(COUNTY_NAM, geometry) %>%\n  left_join(counties_stat, by = \"COUNTY_NAM\")\n\np1 <- ggplot() +\n  # county base map\n  geom_sf(\n    data = counties_stat_sf,\n    aes(fill = percentage_vuln),\n    color = \"white\", size = 0.2\n  ) +\n  # hospitals\n  geom_sf(\n    data = hospitals_proj,\n    shape = 21, fill = \"red\",\n    size = 1.8, alpha = 0.9\n  ) +\n  # legend\n  scale_fill_viridis_c(\n    name = \"% vulnerable tracts\",\n    labels = label_percent(accuracy = 1),\n    limits = c(0, 1),\n    option = \"C\",      \n    direction = -1\n  ) +\n  coord_sf() +\n  theme_void(base_size = 12) +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text  = element_text(size = 9),\n    plot.title   = element_text(face = \"bold\", size = 16),\n    plot.subtitle= element_text(size = 12)\n  ) +\n  labs(\n    title    = \"Healthcare Access Challenges by County\",\n    subtitle = \"share of vulnerable census tracts\",\n    caption  = \"Source: analysis based on income and percentage of people over 65 years old.\"\n  ) +\n  guides(fill = guide_colorbar(\n    barheight = unit(70, \"pt\"),\n    barwidth  = unit(8,  \"pt\"),\n    ticks.colour = \"black\"\n  ))\n\np1\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\np2 <- ggplot() +\n  # tract base map\n  geom_sf(\n    data = census_tracts,\n    color = \"grey\", size = 0.1\n  ) +\n  # county base map\n  geom_sf(\n    data = pa_counties,\n    color = \"lightblue\", size = 0.5,fill = NA,\n  ) +\n  # hospitals\n  geom_sf(\n    data = hospitals_proj,\n    shape = 16, color = \"red\",\n    size = 1, alpha = 0.9\n  ) +\n  # underserved community\n  geom_sf(\n    data = undeserved,\n    color = \"blue\"\n  )+\n  coord_sf() +\n  theme_void(base_size = 12) +\n  theme(\n    plot.title   = element_text(face = \"bold\", size = 16),\n    plot.subtitle= element_text(size = 12)\n  ) +\n  labs(\n    title    = \"Underserved Communities\",\n    subtitle = \"Blue tracts represent underserved communities; red points show hospital locations.\"\n  ) +\n  guides(fill = guide_colorbar(\n    barheight = unit(70, \"pt\"),\n    barwidth  = unit(8,  \"pt\"),\n    ticks.colour = \"black\"\n  ))\n\np2\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#only one very small blue tract in the center of the map\n```\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\n# Histogram or density plot of distances\nggplot(vulnerable_tracts_proj) +\n  aes(x = dist_to_hospital_mi) +\n  geom_histogram(bins = 15, fill = \"steelblue\", alpha = 0.7) +\n  labs(\n    title = \"Distribution of distance to the nearest hospital\",\n    x = \"distance to the nearest hospital\",\n    y = \"Number of vulnerable tracts\",\n    caption  = \"Most of tracts have distance between 0 and 5.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Box plot comparing distances across regions\nggplot(vulnerable_tracts_proj) +\n  aes(x = NAMELSADCO, y = dist_to_hospital_mi, fill = NAMELSADCO) +\n  geom_boxplot() +\n  labs(\n    title = \"Distances by County Category\",\n    x = \"County\",\n    y = \"Distance\",\n    caption  = \"While most counties show little variation, four counties have huge internal differences\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")+\n  theme(\n  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7)\n)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Bar chart of underserved tracts by county\n#only 1 underserved tracts in my study, it is Census Tract 9601 in the Cameron County\n\n\n# Scatter plot of distance vs. vulnerable population size\nggplot(vulnerable_tracts_proj) +\n  aes(x = dist_to_hospital_mi, y = total_populationE) +\n  geom_point(color = \"steelblue\", alpha = 0.6, size = 2) +\n  geom_smooth(\n    method = \"lm\",              \n    se = TRUE,                  \n    color = \"darkred\",          \n    fill = \"pink\",              \n    linewidth = 1\n  ) +\n  labs(\n    title = \"distance vs. vulnerable population size\",\n    x = \"Distance to the nearest hospital\",\n    y = \"Vulnerable population size\",\n    caption  = str_wrap(\"More vulnerable population, little distance to hospital. Since hospitals are designed to located near population clusters, and we didn't limit this effect in this study \", width = 90)\n  ) +\n  theme_minimal() +\n  scale_x_continuous() +\n  scale_y_continuous(labels = comma)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nlibrary(sf)\n\nschools <- st_read(\"Data/Schools/Schools.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools' from data source \n  `/Users/jinhengcen/Documents/portfolio-setup-CenJinHeng/assignments/assignment_2/data/Schools/Schools.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 495 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8378628 ymin: 4852555 xmax: -8345686 ymax: 4884813\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ncrime <- st_read(\"Data/Crime/Crime.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Crime' from data source \n  `/Users/jinhengcen/Documents/portfolio-setup-CenJinHeng/assignments/assignment_2/data/Crime/Crime.shp' \n  using driver `ESRI Shapefile'\nreplacing null geometries with empty geometries\nSimple feature collection with 160388 features and 13 fields (with 6744 geometries empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.50237 ymin: 39.87688 xmax: -74.95784 ymax: 42.22434\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbike_network <- st_read(\"Data/Bike_Network/Bike_Network.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Bike_Network' from data source \n  `/Users/jinhengcen/Documents/portfolio-setup-CenJinHeng/assignments/assignment_2/data/Bike_Network/Bike_Network.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5225 features and 8 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: -8378937 ymin: 4847835 xmax: -8345146 ymax: 4883978\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nschools <- st_transform(schools, 2272)\ncrime <- st_transform(crime, 2272)\nbike_network <- st_transform(bike_network, 2272)\n\nlibrary(dplyr)\nlibrary(ggplot2)\n\n## school type\nschools %>%\n  st_drop_geometry() %>%\n  count(type_speci, sort = TRUE) %>%\n  ggplot(aes(x = reorder(type_speci, n), y = n)) +\n  geom_bar(stat = \"identity\", fill = \"lightblue\") +\n  coord_flip() +\n  labs(\n    title = \"Distribution of school types\",\n    x = \"School type\",\n    y = \"Number\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Crime Hour\ncrime %>%\n  st_drop_geometry() %>%\n  count(hour) %>%\n  ggplot(aes(x = hour, y = n)) +\n  geom_col(fill = \"firebrick\") +\n  labs(\n    title = \"Distribution of crime hour\",\n    x = \"Hour\",\n    y = \"Number of incidents\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#crime types\ncrime %>%\n  st_drop_geometry() %>%\n  count(text_gener, sort = TRUE) %>%\n  slice_max(n, n = 10) %>%  \n  ggplot(aes(x = reorder(text_gener, n), y = n)) +\n  geom_bar(stat = \"identity\", fill = \"orange\") +\n  coord_flip() +\n  labs(\n    title = \"Top 10 Crime Types\",\n    x = \"Types\",\n    y = \"Number of incidents\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# Bike lane\nbike_length_summary <- bike_network %>%\n  st_drop_geometry() %>%\n  group_by(TYPE) %>%\n  summarise(total_length = sum(Shape__Len, na.rm = TRUE)) %>%\n  arrange(desc(total_length))\n\nggplot(bike_length_summary, aes(x = reorder(TYPE, total_length), y = total_length)) +\n  geom_bar(stat = \"identity\", fill = \"forestgreen\") +\n  coord_flip() +\n  labs(\n    title = \"Distribution of Bike Lane Type\",\n    x = \"Type\",\n    y = \"Total Length\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nThree data sets are chosen:\n  - Schools data in shp format\n  - Crime incidents data points in shp format\n  - Bike_Network in shp format\nSince I am going to calculate some metrics like the numbers of crime incidents and the length of bike lanes within school buffers, these data are needed. \n- What is the data source and date?\nThey are all from OpenDataPhilly. All of them are up_to_date. The crime incidents data is from 2024, because we are in the October of the 2025, so we don't have data for the whole 2025. Using 2024 can avoid some time variation.\n- How many features does it contain?\nAll of them have geometry, which means we can run them in spatial analysis. For the school data set, we got names, types, grade levels, phone numbers, street names, and zip codes. For the crime data, we have precise time, crime types, location details. For the bike network data, we knew street names, types, lengths and oneway.  \n- What CRS is it in? Did you need to transform it?\nEPSG:2272, which is used in south Pennsylvania.\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\nMy question is **\"Are school zones safe for walking/biking, or are they crime hotspots?\"**\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\n# I have loaded data sets and make simple statistical analysis for each of them in the previous chunk\n\n# Create buffer for schools\n\nschools <- schools %>% mutate(school_id = row_number())\nzones <- st_buffer(schools, dist = 1000)\n\n# Calculate the crime number\n\ncrime_by_zone <- crime %>%\n  st_join(zones %>% select(school_id), join = st_within) %>%\n  st_drop_geometry() %>%\n  count(school_id, name = \"crime_count\")\n\n\n# Calculate the bike lane length\nbike_in_zone <- st_intersection(bike_network, zones %>% select(school_id))\n\nbike_len_by_zone <- bike_in_zone %>%\n  mutate(len_ft = as.numeric(st_length(.))) %>% \n  st_drop_geometry() %>%\n  group_by(school_id) %>%\n  summarise(bike_len_ft = sum(len_ft, na.rm = TRUE), .groups = \"drop\")\n\n# Combine the result\nzone_stats <- zones %>%\n  left_join(crime_by_zone,    by = \"school_id\") %>%\n  left_join(bike_len_by_zone, by = \"school_id\")\n\n# Calculate average number of the crime incidents and bike lane length\nzone_summary <- zone_stats %>%\n  st_drop_geometry() %>%\n  summarise(\n    mean_crime = mean(crime_count, na.rm = TRUE),\n    mean_bike_len = mean(bike_len_ft, na.rm = TRUE)\n  )\n\ncity_summary <- tibble(\n  mean_crime = nrow(crime) / nrow(zones),\n  mean_bike_len = sum(st_length(bike_network)) / nrow(zones)\n)\n\n# Combine results\ncomparison <- rbind(\n  data.frame(Category = \"School Zones\", \n             mean_crime = zone_summary$mean_crime, \n             mean_bike_len = zone_summary$mean_bike_len),\n  data.frame(Category = \"Citywide Average\",\n             mean_crime = city_summary$mean_crime,\n             mean_bike_len = city_summary$mean_bike_len)\n)\n\n# Draw diagram\nggplot(comparison, aes(x = Category, y = mean_crime, fill = Category)) +\n  geom_bar(stat = \"identity\", width = 0.6) +\n  labs(\n    title = \"Comperison of Average Crime Incidents: School Zones VS City\",\n    y = \"Averge Crime Incidents\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(comparison, aes(x = Category, y = mean_bike_len, fill = Category)) +\n  geom_bar(stat = \"identity\", width = 0.6) +\n  labs(\n    title = \"Comperison of Bike Lane Length: School Zones VS City\",\n    y = \"Average Bike Lane Length\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mapping\n\n# Get tracts of Philly\ntracts_phl <- get_acs(\n  geography = \"tract\",\n  state     = \"PA\",\n  county    = \"Philadelphia\",\n  variables = \"B01003_001\",\n  survey    = \"acs5\",\n  year      = 2022,\n  geometry  = TRUE,\n  cache_table = TRUE\n) %>%\n  select(GEOID, NAME, pop = estimate, geometry) %>%\n  st_transform(2272)    \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# point_on_surface\nzone_points <- zone_stats |>\n  mutate(geometry = st_point_on_surface(geometry),\n         bike_len_mile = bike_len_ft / 5280) |>\n  st_as_sf()\n\n# Crime point map\nggplot() +\n  geom_sf(data = tracts_phl, fill = NA, color = \"grey\", linewidth = 0.2) +\n  geom_sf(data = zone_points, aes(size = crime_count), color = \"firebrick\", alpha = 0.6) +\n  scale_size_continuous(name = \"Crime count\", range = c(0, 4)) +\n  labs(title = \"School Zones: Crime Counts (Point size = count)\", x = NULL, y = NULL) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Bike lane point map\nggplot() +\n  geom_sf(data = tracts_phl, fill = NA, color = \"grey\", linewidth = 0.2) +\n  geom_sf(data = zone_points, aes(size = bike_len_mile), color = \"forestgreen\", alpha = 0.6) +\n  scale_size_continuous(name = \"Bike lane (miles)\", range = c(0.1, 2)) +\n  labs(title = \"School Zones: Bike Lane Length (Point size = miles)\", x = NULL, y = NULL) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Cen_Jinheng_Assignment2_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nSchool zones have fewer crime incidents and bike lane length compared to city average. More pedestrian-friendly projects should be applied to school areas. For the spatial difference, higher concentrations of crimes are observed around schools in central and southern Philadelphia. School zones with longer bike lane coverage are mostly located in the city’s core and western areas. Planning efforts should focus on improving safety in school zones with higher crime risks, especially in central and southern Philadelphia. Expanding connected and protected bike lanes around schools can promote safer and more accessible environments for students.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "Cen_Jinheng_Assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}